name: Deploy Dev Stage (Serverless)

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "shared/**"
jobs:
  deploy:
    name: Deploy to AWS Dev
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      STAGE: dev
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------- AWS Credentials ----------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # ---------- Language Setup ----------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "rules/package-lock.json"

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12" # Stable Lambda support

      # ---------- Deploy Events Service (Python) ----------
      # We install requirements in the folder so Serverless can package them
      - name: Install Python Dependencies
        working-directory: ./events
        run: |
          if [ -f requirements.txt ]; then
            python -V
            pip install -r requirements.txt
          fi

      - name: Deploy Events Service
        uses: serverless/github-action@v4
        with:
          entrypoint: /usr/bin/bash
          args: -c "python -V && cd events && serverless deploy --stage dev  --region $AWS_REGION"

      # ---------- Deploy Rules Service (Node.js) ----------
      - name: Install Node Dependencies
        working-directory: ./rules
        run: npm install

      - name: Deploy Rules Service
        uses: serverless/github-action@v4
        with:
          entrypoint: /usr/bin/bash
          args: -c "python -V && cd rules && serverless deploy --stage dev --region $AWS_REGION"
